- hosts: all
# user: hpeadm
  become_method: sudo
  become: yes
  gather_facts: false
  ignore_errors: yes
  tasks:
    - name: updating the passsword policy
      command : passwd -n 7 -x 365 -w 14  hpsb
      register: updated_passwd_policy
    - debug: var=updated_passwd_policy.stdout_lines
    - name: Passwd policy  updated
      command:    chage -l hpsb
      register: passwd_policy_changed
    - debug: var=passwd_policy_changed.stdout_lines

