- hosts: all
# user: buildadm
  become_method: sudo
  become: yes
  gather_facts: false
  ignore_errors: yes
  tasks:
    - name: get the output
      command : uptime
      register: out1
    - debug: var=out1.stdout_lines

