-  hosts: all
   become_method: sudo 
   become:  yes
   gather_facts: false
   ignore_errors: true
   tasks:
     - name:  Add the user
       shell: useradd sps_glo_ibnext17
       register: user_added_successfully
     - debug: var=user_added_successfully.stdout_lines
     - name: Assinging remote wheel permissions
       command: usermod -aG remote sps_glo_ibnext17
       register: Permission_assigned
     - debug: var=Permission_assigned.stdout_lines
