---
- name: Add Users
  hosts: all
  become: yes
  tasks:
   - name: Add a new user
     user:
       name: google
       state: present
- name: Assign Groups to Users
  hosts: all
  become: yes
  tasks:
   - name: Add user to sudo group for administrative privileges
     user:
       name: goggle
       groups: remote
       append: yes
- name: Verify User Details
  hosts: all
  become: yes
  tasks:
   - name: Check user details
     command: id google
     register: user_details
   - name: Display user details
     debug:
       msg: "{{ user_details.stdout }}"
